# Generated by Django 4.2.5 on 2024-04-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lzr_dfinityapi", "0002_coin_canister_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="logs",
            name="amount",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
