# Generated by Django 4.2.5 on 2024-04-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lzr_dfinityapi", "0004_rename_holders_holder_rename_logs_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="holder",
            name="coin",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="lzr_dfinityapi.coin",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coin",
            name="holders",
            field=models.ManyToManyField(
                related_name="coin_holders", to="lzr_dfinityapi.holder"
            ),
        ),
    ]
