# Generated by Django 4.2.5 on 2024-04-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lzr_dfinityapi", "0005_holder_coin_alter_coin_holders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="reserve_balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coin",
            name="total_supply",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="holder",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
