# Generated by Django 4.2.5 on 2024-04-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lzr_dfinityapi",
            "0006_alter_coin_reserve_balance_alter_coin_total_supply_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="reserve_balance",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name="coin",
            name="total_supply",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name="holder",
            name="balance",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name="log",
            name="amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
    ]
